export const FETCH_TEAM_PACKAGES_REQUEST = 'FETCH_TEAM_PACKAGES_REQUEST';
export const FETCH_TEAM_PACKAGES_SUCCESS = 'FETCH_TEAM_PACKAGES_SUCCESS';
export const FETCH_TEAM_PACKAGES_FAILURE = 'FETCH_TEAM_PACKAGES_FAILURE';

export const ADD_PACKAGE_TO_TEAM = 'ADD_PACKAGE_TO_TEAM';
export const CANCEL_TEAM_PACKAGE = 'CANCEL_TEAM_PACKAGE';
